routes:
  - path: /health
    target: http://localhost:3000
    rate_limit:
      rate: 10
      burst: 20
  - path: /events
    target: http://localhost:4000
    rate_limit:
      rate: 10
      burst: 20